[project]
name = "mootdx2"
version = "1.0.6"
description = "通达信数据读取接口."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "bopo", email = "ibopo@126.com" }
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "httpx>=0.25.0",
    "tenacity>=8.1.0",
    "tdxpy>=0.2.5",
    "tqdm>=4.66.0",
    "prettytable>=3.5.0",
    "click>=8.1.3",
    "typing-extensions>=4.5.0",
    "mini-racer>=0.12.0",
    "pyyaml>=6.0.3",
]

[project.urls]
Homepage = "https://www.mootdx.com"
Repository = "https://github.com/mootdx/mootdx"

[project.scripts]
mootdx2 = "mootdx2.__main__:entry"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["mootdx2"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-p no:warnings"
log_cli = 0
log_cli_level = "DEBUG"

[dependency-groups]
dev = [
    "pytest>=7.3.1",
    "pytest-cov>=4.0.0",
    "freezegun>=1.2.2",
    "tox",
    "ruff",
    "matplotlib>=3.7.5",
    "mplfinance>=0.12.10b0",
]

[tool.commitizen]
tag_format = "v$version"
annotated_tag = true
changelog_file = "docs/history.md"
changelog_incremental = true
update_changelog_on_bump = true
version_provider = "pep621"
version_files = [
    "mootdx2/__init__.py:__version__",
]
